[package]
name = "bust"
version = "0.1.0"
edition = "2018"

[lib]
name = "bust"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 =  {version = "0.13.2", features = ["extension-module"]}
